### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by oacostam** [dotnet/AspNetCore.Docs.es-es#49]
The docs should explain how to setup the site in IIS, for instance, what physical path should be used, the same as project? Or it's needed to deploy the project to some location before debugging?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: f5477f20-bdbf-ae0b-63b4-8bf6789f7a48
* Version Independent ID: fa9dc362-76a4-5d11-f457-b3d8550f9997
* Content: [Compatibilidad de IIS de tiempo de desarrollo en Visual Studio para ASP.NET Core](https://docs.microsoft.com/es-es/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/iis/development-time-iis-support.md](https://github.com/dotnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/host-and-deploy/iis/development-time-iis-support.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @oacostam
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @oacostam, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/17839. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
